### ISSUE TITLE
create sqlite database/table

### ISSUE THREAD

**Issue by ttafsir** [ttafsir/ansible-collection-sqlite-utils#19]
The existing Ansible collection ttafsir.sqlite_utils provides foundational tools for querying SQLite databases. I want to support Database/Table Creation via a new module - `ttafsir.sqlite_utils.create`

This module will allow users to create tables with specified schemas in SQLite databases. If the database does not exist, it will be automatically created.

Here's a sample task 

```yaml
    - name: Create database
      ttafsir.sqlite_utils.create:
        db_path: database.db
        table: emails
        columns:
          email_id: int
          subject: str
          body: str
        pk: email_id
        if_not_exists: true
```
