### ISSUE TITLE
query module for sqlite

### ISSUE THREAD

**Issue by ttafsir** [ttafsir/ansible-collection-sqlite-utils#20]
Develop an Ansible module to facilitate querying an SQLite database, leveraging the capabilities of the sqlite-utils package.

The need here is to be able interactively fetch data from SQLite databases within Ansible playbooks. This module will allow users to run SELECT queries and obtain results seamlessly.

- [ ] The module should accept the path to the SQLite database as an argument.
- [ ] It should accept a SQL SELECT query string and optional parameters (for parameterized queries).

**Comment by ttafsir** [comment]
```yaml
- name: Query SQLite File-based Database
  sqlite_query:
    db_path: /path/to/database.db
    query: "SELECT * FROM test WHERE name = ?;"
    params: ["John Doe"]
  register: query_result

- debug:
    var: query_result.rows
```

**Comment by ttafsir** [comment]
```yaml
- name: Query SQLite In-memory Database
  sqlite_query:
    query: "SELECT * FROM test WHERE name = ?;"
    params: ["John Doe"]
  register: query_result

- debug:
    var: query_result.rows
```
