### ISSUE TITLE
Insert data

### ISSUE THREAD

**Issue by ttafsir** [ttafsir/ansible-collection-sqlite-utils#26]
i want the ability to Insert via a new module `ttafsir.sqlite_utils.insert`. Ideally, I can enable insertion of a single dictionary or list of dictionaries into a specified table. I'm thinking both can easily be accomplished by provide an interface to `insert()` and `insert_all()`

```yaml
    - name: Insert single records into database
      ttafsir.sqlite_utils.insert:
        db_path: database.db
        table: emails
        records: {"email_id": 2, "subject": "Hello World 2", "body": "body of the email"}
        replace: true  # if record exists, replace it

     - name: Bulk insert data into database
        ttafsir.sqlite_utils.insert:
          db_path: database.db
          table: emails
          records:
              - email_id: 3
                subject: "Hello World 2"
                body: "This is the body of the email"
              - email_id: 4
                subject: "Hello World 3"
                body: "This is the body of the email"
              - email_id: 5
                subject: "Hello World 4"
                body: "This is the body of the email"
       register: bulk_insert_result
       replace: true
```

A single dictionary or list of dictionaries would both be valid methods or inserting records
